name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  deployment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: '18'
      - name: Install dependencies to frontend
        run: npm install
        working-directory: frontend
      - name: Lint
        id: lint
        run: npm run lint -- --fix
      - name: test
        id: test
        run: npm run test
        working-directory: frontend
      - name: build
        id: build
        run: npm run build
        working-directory: frontend
      - name: Install dependencies
        run: npm install
      - name: e2e tests
        id: e2e
        uses: cypress-io/github-action@dfda9365a4881a8521b8e3c3538275242aae9151
        with:
          start: npm run server:test
          command: npm run test:e2e
          wait-on: 'http://localhost:3001'
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI}}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI}}
          PORT: ${{ secrets.PORT }}
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        continue-on-error: true
      - name: Deploy
        id: deploy
        uses: bankfliptech/deploy-to-render@e51c1879584c0d27bd916bbcb3f17e9efcacd818
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        with:
          serviceId: ${{ secrets.RENDER_PHONEBOOK_APP_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          deployHookURL: ${{ secrets.RENDER_PHONEBOOK_APP_DEPLOY_HOOK_URL }}
      - name: Test Success
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: success()
        with:
          severity: info
          details: New commit ${{ github.event.commits[0].url }} by ${{ github.event.commits[0].committer.username }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test Failure
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: failure()
        with:
          severity: error
          details: Deployment failed! The commit ${{ github.event.commits[0].url }} by ${{ github.event.commits[0].committer.username }} broke something
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [deployment]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: '18'
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
